# Kakanai Backend

[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 600 --workers 1"
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[variables]
PYTHON_VERSION = "3.11"
